In [2]:
import pandas as pd
import numpy as np

In [3]:
df_bl = pd.read_csv('./03_results/bothunter_location.csv').iloc[:,1:]
df_ble = pd.read_csv('./03_results/bothunter_location_emotions.csv').iloc[:,1:]
df_blm = pd.read_csv('./03_results/bothunter_location_morals.csv').iloc[:,1:]

In [4]:
df_bl

,location,region,lat,lon,prediction,count,percentage
0,`ajlun-20-jo,asia/amman,32.33385,35.75238,0.0,161,91.48
1,`ajlun-20-jo,asia/amman,32.33385,35.75238,1.0,15,8.52
2,`ajman-02-ae,asia/dubai,25.41111,55.43504,0.0,314,72.52
3,`ajman-02-ae,asia/dubai,25.41111,55.43504,1.0,119,27.48
4,`ar`ar-15-sa,asia/riyadh,30.97531,41.03808,0.0,70,59.32
...,...,...,...,...,...,...,...
5556,zurich-zh112-ch,europe/zurich,47.36667,8.55000,1.0,6308,62.31
5557,zwickau-13-de,europe/berlin,50.72724,12.48839,0.0,101,63.92
5558,zwickau-13-de,europe/berlin,50.72724,12.48839,1.0,57,36.08
5559,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,0.0,505,73.08
5560,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,1.0,186,26.92

In [5]:
df_bl[df_bl['region']=='prince']

,location,region,lat,lon,prediction,count,percentage
919,cap haitien-09-au,prince,19.75778,-72.20417,0.0,23,76.67
920,cap haitien-09-au,prince,19.75778,-72.20417,1.0,7,23.33
1781,gonaives-06-au,prince,19.45000,-72.68333,0.0,44,73.33
1782,gonaives-06-au,prince,19.45000,-72.68333,1.0,16,26.67
2180,jacmel-13-au,prince,18.23417,-72.53472,0.0,1,100.00
2726,les cayes-12-au,prince,18.20000,-73.75000,0.0,19,86.36
2727,les cayes-12-au,prince,18.20000,-73.75000,1.0,3,13.64
3902,port au prince-11-au,prince,18.53917,-72.33500,0.0,795,90.86
3903,port au prince-11-au,prince,18.53917,-72.33500,1.0,80,9.14

In [6]:
list(set(df_bl['region']))

['asia/damascus',
 'europe/london',
 'australia/darwin',
 'asia/dili',
 'america/montevideo',
 'europe/tirane',
 'asia/jerusalem',
 'america/maceio',
 'atlantic/reykjavik',
 'asia/irkutsk',
 'australia/melbourne',
 'america/la_paz',
 'africa/accra',
 'asia/beirut',
 'asia/vladivostok',
 'america/caracas',
 'africa/freetown',
 'america/recife',
 'europe/zagreb',
 'asia/seoul',
 'prince',
 'asia/pontianak',
 'america/santarem',
 'africa/lagos',
 'america/curacao',
 'asia/bishkek',
 'europe/amsterdam',
 'america/cuiaba',
 'america/tijuana',
 'america/halifax',
 'africa/brazzaville',
 'africa/libreville',
 'africa/harare',
 'asia/colombo',
 'europe/oslo',
 'europe/lisbon',
 'asia/taipei',
 'america/boise',
 'america/santo_domingo',
 'america/st_johns',
 'africa/casablanca',
 'america/fortaleza',
 'africa/lome',
 'america/phoenix',
 'atlantic/madeira',
 'asia/baghdad',
 'indian/maldives',
 'africa/maseru',
 'europe/athens',
 'europe/warsaw',
 'asia/jakarta',
 'america/tegucigalpa',
 'america/los_angeles',
 'america/guadeloupe',
 'europe/helsinki',
 'america/lima',
 'asia/dubai',
 'europe/istanbul',
 'america/argentina/jujuy',
 'africa/windhoek',
 'asia/omsk',
 'australia/adelaide',
 'america/nassau',
 'america/santiago',
 'africa/kinshasa',
 'america/guayaquil',
 'europe/kiev',
 'europe/ljubljana',
 'europe/prague',
 'asia/yekaterinburg',
 'atlantic/cape_verde',
 'asia/dushanbe',
 'asia/novokuznetsk',
 'america/anchorage',
 'asia/hong_kong',
 'asia/karachi',
 'asia/makassar',
 'america/montreal',
 'asia/krasnoyarsk',
 'asia/manila',
 'asia/gaza',
 'africa/dakar',
 'africa/addis_ababa',
 'europe/zurich',
 'america/kentucky/louisville',
 'asia/baku',
 'america/havana',
 'america/detroit',
 'asia/yakutsk',
 'africa/bujumbura',
 'america/guatemala',
 'africa/kampala',
 'america/new_york',
 'asia/bahrain',
 'europe/belgrade',
 'america/argentina/mendoza',
 'asia/harbin',
 'america/port_of_spain',
 'africa/ouagadougou',
 'america/mazatlan',
 'asia/yerevan',
 'europe/uzhgorod',
 'america/araguaina',
 'australia/perth',
 'pacific/honolulu',
 'africa/luanda',
 'asia/muscat',
 'asia/kolkata',
 'america/belem',
 'america/indiana/indianapolis',
 'america/costa_rica',
 'america/argentina/cordoba',
 'america/monterrey',
 'asia/tehran',
 'asia/novosibirsk',
 'asia/kuwait',
 'america/manaus',
 'europe/copenhagen',
 'asia/riyadh',
 'america/denver',
 'asia/aqtobe',
 'africa/nairobi',
 'europe/brussels',
 'pacific/port_moresby',
 'europe/berlin',
 'europe/tallinn',
 'america/edmonton',
 'america/jamaica',
 'asia/sakhalin',
 'pacific/noumea',
 'america/el_salvador',
 'europe/sofia',
 'europe/skopje',
 'australia/brisbane',
 'europe/volgograd',
 'asia/tokyo',
 'europe/paris',
 'america/porto_velho',
 'america/regina',
 'europe/kaliningrad',
 'africa/douala',
 'america/argentina/buenos_aires',
 'indian/antananarivo',
 'america/guyana',
 'america/sao_paulo',
 'europe/samara',
 'america/argentina/catamarca',
 'asia/ashgabat',
 'africa/monrovia',
 'africa/abidjan',
 'america/chicago',
 'asia/aqtau',
 'africa/bamako',
 'asia/tbilisi',
 'africa/algiers',
 'america/rio_branco',
 'america/argentina/tucuman',
 'africa/lusaka',
 'africa/nouakchott',
 'asia/kamchatka',
 'asia/tashkent',
 'america/asuncion',
 'america/argentina/san_luis',
 'asia/chongqing',
 'america/martinique',
 'africa/tripoli',
 'america/argentina/la_rioja',
 'africa/dar_es_salaam',
 'africa/tunis',
 'africa/djibouti',
 'asia/kabul',
 'europe/bucharest',
 'asia/ho_chi_minh',
 'asia/dhaka',
 'america/moncton',
 'asia/qatar',
 'asia/kuching',
 'indian/reunion',
 'pacific/auckland',
 'novo',
 'america/chihuahua',
 'asia/pyongyang',
 'africa/kigali',
 'america/campo_grande',
 'asia/macau',
 'america/argentina/san_juan',
 'africa/lubumbashi',
 'america/glace_bay',
 'africa/cairo',
 'asia/shanghai',
 'europe/bratislava',
 'asia/vientiane',
 'europe/podgorica',
 'europe/madrid',
 'america/bahia',
 'asia/jayapura',
 'america/aruba',
 'america/hermosillo',
 'europe/stockholm',
 'asia/qyzylorda',
 'america/boa_vista',
 'indian/mauritius',
 'asia/phnom_penh',
 'europe/dublin',
 'america/bogota',
 'africa/maputo',
 'europe/zaporozhye',
 'asia/bangkok',
 'europe/minsk',
 'america/vancouver',
 'asia/samarkand',
 'asia/aden',
 'africa/gaborone',
 'europe/vilnius',
 'asia/urumqi',
 'africa/mbabane',
 'africa/niamey',
 'europe/vienna',
 'europe/rome',
 'america/paramaribo',
 'asia/almaty',
 'africa/johannesburg',
 'asia/nicosia',
 'europe/simferopol',
 'europe/sarajevo',
 'europe/chisinau',
 'america/toronto',
 'america/matamoros',
 'africa/khartoum',
 'asia/singapore',
 'america/managua',
 'asia/kathmandu',
 'asia/amman',
 'australia/sydney',
 'america/argentina/salta',
 'america/panama',
 'africa/mogadishu',
 'america/winnipeg',
 'america/ojinaga',
 'asia/kashgar',
 'africa/el_aaiun',
 'asia/hebron',
 'europe/budapest',
 'africa/blantyre',
 'europe/moscow',
 'africa/conakry',
 'america/cayenne',
 'asia/kuala_lumpur',
 'europe/riga',
 'america/cancun',
 'america/puerto_rico',
 'america/merida',
 'asia/ulaanbaatar',
 'asia/rangoon',
 'america/mexico_city',
 'atlantic/canary']

In [7]:
region_to_countries = {
    'america/lima' : 'Peru',
    'asia/manila' : 'Philippines',
    'america/chihuahua' : 'Mexico',
    'asia/pyongyang' : 'North Korea',
    'asia/pontianak' : 'Indonesia',
    'australia/sydney' : 'Australia',
    'europe/simferopol' : 'Ukraine',
    'asia/sakhalin' : 'Russia',
    'america/argentina/san_luis' : 'Argentina',
    'asia/dushanbe' : 'Tajikistan',
    'america/santarem' : 'Brazil',
    'america/tegucigalpa' : 'Honduras',
    'america/tijuana' : 'Mexico',
    'asia/irkutsk' : 'Russia',
    'asia/bangkok' : 'Thailand',
    'europe/istanbul' : 'Turkey',
    'america/argentina/la_rioja' : 'Argentina',
    'america/argentina/catamarca' : 'Argentina',
    'africa/kampala' : 'Uganda',
    'asia/beirut' : 'Lebanon',
    'asia/yekaterinburg' : 'Russia',
    'europe/berlin' :  'Germany',
    'america/montreal' : 'Canada',
    'asia/qyzylorda' : 'Kazakhstan',
    'asia/kabul' : 'Afghanistan',
    'asia/baghdad' : 'Iraq',
    'prince' : 'Haiti',
    'america/matamoros' : 'Mexico',
    'asia/makassar' : 'Indonesia',
    'africa/luanda' : 'Angola',
    'europe/ljubljana' : 'Slovenia',
    'america/indiana/indianapolis' : 'United States',
    'america/vancouver' : 'Canada',
    'america/kentucky/louisville' : 'United States',
    'africa/maseru' : 'Lesotho',
    'europe/rome' : 'Italy',
    'america/argentina/salta' : 'Argentina',
    'australia/adelaide' : 'Australia',
    'africa/libreville' : 'Gabon',
    'asia/vientiane' : 'Laos',
    'asia/jakarta' : 'Indonesia',
    'asia/riyadh' : 'Saudi Arabia',
    'asia/macau' : 'China',
    'asia/dubai' : 'United Arab Emirates',
    'america/nassau' : 'Bahamas',
    'america/boa_vista' : 'Cape Verde', 
    'europe/london' : 'United Kingdom',
    'asia/amman' : 'Jordan',
    'europe/uzhgorod' : 'Ukraine', 
    'america/santiago' : 'Chile',
    'europe/skopje' : 'North Macedonia',
    'africa/tripoli' : 'Libya',
    'asia/chongqing' : 'China',
    'asia/ashgabat' : 'Turkmenistan',
    'europe/minsk' : 'Russia',
    'america/regina' : 'Canada',
    'america/asuncion' : 'Paraguay',
    'america/santo_domingo' : 'Dominican Republic',
    'america/belem' : 'Brazil',
    'asia/kuching' : 'Malasia',
    'africa/monrovia' : 'Liberia',
    'europe/zagreb' : 'Croatia',
    'asia/omsk' : 'Russia',
    'asia/hong_kong' : 'China',
    'africa/accra' : 'Ghana',
    'africa/blantyre' : 'Malawi',
    'asia/qatar' : 'Qatar',
    'america/argentina/tucuman' : 'Argentina', 
    'europe/budapest' : 'Hungary',
    'europe/dublin' :  'Ireland',
    'africa/algiers' : 'Algeria', 
    'america/argentina/buenos_aires' : 'Argentina',
    'africa/addis_ababa' : 'Ethiopia',
    'asia/novosibirsk' : 'Russia',
    'europe/warsaw' : 'Poland',
    'america/guayaquil' : 'Ecuador',
    'america/recife' : 'Brazil',
    'australia/brisbane' : 'Australia',
    'asia/seoul' : 'South Korea',
    'asia/kolkata' : 'India',
    'asia/bishkek' : 'Kyrgyzstan',
    'asia/kamchatka' : 'Russia',
    'africa/douala' : 'Cameroon',
    'atlantic/cape_verde' : 'Cape Verde',
    'america/rio_branco' : 'Brazil',
    'asia/tbilisi' : 'Georgia',
    'america/cuiaba' : 'Brazil',
    'america/boise' : 'United States',
    'america/la_paz' : 'Bolivia',
    'africa/kigali' : 'Rwanda',
    'africa/brazzaville' : 'Republic of the Congo',
    'africa/abidjan' : 'Ivory Coast',
    'africa/mogadishu': 'Somalia',
    'europe/lisbon' : 'Portugal',
    'africa/el_aaiun' : 'Western Sahara',
    'africa/bamako' : 'Mali',
    'europe/belgrade' : 'Serbia',
    'australia/melbourne' : 'Australia',
    'asia/bahrain' : 'Bahrain',
    'africa/conakry' : 'Guinea',
    'asia/hebron' : 'Palestine',
    'pacific/honolulu' : 'United States',
    'europe/samara' : 'Russia',
    'indian/mauritius' : 'Mauritius',
    'asia/dhaka' : 'Bangladesh',
    'america/winnipeg' : 'Canada',
    'europe/tallinn' : 'Estonia',
    'asia/dili' : 'East Timor',
    'america/managua' : 'Nicaragua',
    'europe/moscow' : 'Russia',
    'asia/jerusalem' : 'Israel',
    'europe/kaliningrad' : 'Russia',
    'america/porto_velho' : 'Brazil',
    'america/maceio' : 'Brazil',
    'atlantic/reykjavik' : 'Iceland',
    'europe/prague' : 'Czech Republic',
    'asia/urumqi' : 'China',
    'europe/stockholm' : 'Sweden',
    'america/halifax' : 'Canada',
    'asia/shanghai' : 'China',
    'asia/gaza': 'Palestine',
    'europe/podgorica' : 'Montenegro',  
    'asia/karachi' : 'Pakistan',
    'america/guyana' : 'Guyana',
    'africa/cairo' : 'Egypt',
    'africa/lagos' : 'Nigeria',
    'asia/colombo' : 'Sri Lanka',
    'america/edmonton' : 'Canada',
    'europe/kiev' : 'Ukraine',
    'europe/madrid' : 'Spain',
    'asia/kathmandu': 'Nepal',
    'europe/copenhagen' : 'Denmark',
    'america/araguaina' : 'Brazil',
    'africa/djibouti' : 'Djibouti',
    'america/merida' : 'Mexico',
    'europe/paris' : 'France',
    'africa/nairobi' : 'Kenya',
    'america/ojinaga' : 'Mexico',
    'atlantic/madeira' : 'Portugal',
    'africa/niamey' : 'Niger',
    'europe/zaporozhye' : 'Ukraine',
    'asia/rangoon' : 'Myanmar',
    'america/sao_paulo' : 'Brazil',
    'america/monterrey' : 'Mexico',
    'europe/oslo' : 'Norway',
    'america/hermosillo' : 'Mexico',
    'asia/singapore' : 'Singapore',
    'africa/lome' : 'Togo',
    'america/argentina/san_juan' : 'Argentina',
    'africa/dar_es_salaam' : 'Tanzania',
    'asia/aqtau' : 'Kazakhstan',
    'america/phoenix' : 'United States',
    'europe/bucharest' : 'Romania',
    'europe/amsterdam' : 'Netherlands',
    'africa/freetown' : 'Sierra Leone',
    'asia/novokuznetsk' : 'Russia',
    'indian/reunion' : 'France',
    'america/bahia' : 'Brazil',
    'novo' : 'Benin',
    'asia/kuala_lumpur' : 'Malaysia',
    'america/curacao' : 'Curacao',
    'america/panama' : 'Panama',
    'europe/vienna' : 'Austria',
    'africa/casablanca' : 'Morocco',
    'asia/damascus' : 'Syria',
    'america/paramaribo' : 'Suriname',
    'europe/helsinki' : 'Finland',
    'america/moncton' : 'Canada',
    'asia/phnom_penh' : 'Cambodia',
    'america/aruba' : 'Aruba',
    'europe/tirane' : 'Albania',
    'america/manaus' : 'Brazil',
    'america/mexico_city' : 'Mexico',
    'africa/tunis' : 'Tunisia',
    'asia/yerevan' : 'Armenia',
    'america/los_angeles' : 'United States',
    'america/cancun' : 'Mexico',
    'australia/perth' : 'Australia',
    'europe/athens' : 'Greece',
    'america/anchorage' : 'United States',
    'europe/chisinau' : 'Moldova',
    'asia/baku' : 'Azerbaijan',
    'asia/tehran' : 'Iran',
    'america/montevideo' : 'Uruguay',
    'africa/gaborone' : 'Botswana',
    'america/denver' : 'United States',
    'asia/kuwait' : 'Kuwait',
    'asia/jayapura' : 'Indonesia',
    'america/caracas' : 'Venezuela',
    'africa/windhoek' : 'Namibia',
    'indian/antananarivo' : 'Madagascar',
    'europe/vilnius' : 'Lithuania',
    'asia/tokyo' : 'Japan',
    'asia/almaty' : 'Kazakhstan',
    'africa/nouakchott' : 'Mauritania',
    'asia/samarkand' : 'Uzbekistan',
    'america/st_johns' : 'United States',
    'america/argentina/mendoza' : 'Argentina',
    'asia/kashgar' : 'China',
    'asia/nicosia' : 'Cyprus',
    'america/martinique' : 'France',
    'europe/brussels' : 'Belgium',
    'asia/vladivostok' : 'Russia',
    'indian/maldives' : 'Maldives',
    'africa/kinshasa' : 'Democratic Republic of the Congo',
    'europe/zurich' : 'Switzerland', 
    'africa/maputo' : 'Mozambique',
    'asia/tashkent' : 'Uzbekistan',
    'africa/dakar' : 'Senegal',
    'asia/aden' : 'Yemen',
    'america/cayenne' : 'French Guiana',
    'atlantic/canary' : 'Spain',
    'america/jamaica' : 'Jamaica',
    'europe/riga' : 'Latvia',
    'africa/harare' : 'Zimbabwe',
    'america/toronto' : 'Canada',
    'asia/yakutsk' : 'Russia',
    'america/new_york' : 'United States',
    'africa/lusaka' : 'Zambia',
    'africa/mbabane' : 'Swaziland',
    'australia/darwin' : 'Australia',
    'america/port_of_spain' : 'Trinidad and Tobago',
    'america/costa_rica' : 'Costa Rica',
    'europe/volgograd' : 'Russia',
    'america/glace_bay' : 'Canada',
    'america/detroit' : 'United States',
    'asia/muscat' : 'Oman',
    'asia/harbin' : 'China',
    'pacific/port_moresby' : 'Papua New Guinea',
    'africa/lubumbashi' : 'Democratic Republic of the Congo',
    'asia/taipei' : 'Taiwan',
    'pacific/noumea' : 'New Caledonia',
    'america/chicago' : 'United States',
    'america/havana' : 'Cuba',
    'america/argentina/jujuy' : 'Argentina',
    'america/guadeloupe' : 'France',
    'america/argentina/cordoba' : 'Argentina',
    'africa/khartoum' : 'Sudan',
    'africa/johannesburg' : 'South Africa',
    'europe/sofia' : 'Bulgaria',
    'pacific/auckland' : 'New Zealand',
    'europe/sarajevo' : 'Bosnia',
    'europe/bratislava' : 'Slovakia',
    'asia/krasnoyarsk' : 'Russia',
    'asia/aqtobe' : 'Kazakhstan',
    'america/fortaleza' : 'Brazil',
    'america/puerto_rico' : 'Puerto Rico',
    'africa/ouagadougou' : 'Burkina Faso',
    'asia/ulaanbaatar' : 'Mongolia',
    'america/campo_grande' : 'Brazil',
    'africa/bujumbura' : 'Burundi',
    'america/el_salvador' : 'El Salvador',
    'america/bogota' : 'Colombia',
    'america/mazatlan' : 'Mexico',
    'asia/ho_chi_minh' : 'Vietnam',
    'america/guatemala' : 'Guatemala'}

In [8]:
df_bl['country'] = df_bl['region'].replace(region_to_countries)

In [9]:
df_bl

,location,region,lat,lon,prediction,count,percentage,country
0,`ajlun-20-jo,asia/amman,32.33385,35.75238,0.0,161,91.48,Jordan
1,`ajlun-20-jo,asia/amman,32.33385,35.75238,1.0,15,8.52,Jordan
2,`ajman-02-ae,asia/dubai,25.41111,55.43504,0.0,314,72.52,United Arab Emirates
3,`ajman-02-ae,asia/dubai,25.41111,55.43504,1.0,119,27.48,United Arab Emirates
4,`ar`ar-15-sa,asia/riyadh,30.97531,41.03808,0.0,70,59.32,Saudi Arabia
...,...,...,...,...,...,...,...,...
5556,zurich-zh112-ch,europe/zurich,47.36667,8.55000,1.0,6308,62.31,Switzerland
5557,zwickau-13-de,europe/berlin,50.72724,12.48839,0.0,101,63.92,Germany
5558,zwickau-13-de,europe/berlin,50.72724,12.48839,1.0,57,36.08,Germany
5559,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,0.0,505,73.08,Netherlands
5560,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,1.0,186,26.92,Netherlands

In [10]:
df_bl.to_csv('./Analysis/df_bl.csv')

In [11]:
df_ble['country'] = df_ble['region'].replace(region_to_countries)
df_ble

,location,region,lat,lon,prediction,anger,disgust,fear,joy,neutral,sadness,surprise,country
0,`ajlun-20-jo,asia/amman,32.33385,35.75238,0.0,0.157472,0.013708,0.562638,0.108387,0.108624,0.032528,0.016644,Jordan
1,`ajlun-20-jo,asia/amman,32.33385,35.75238,1.0,0.138439,0.016309,0.525496,0.058550,0.207979,0.034809,0.018420,Jordan
2,`ajman-02-ae,asia/dubai,25.41111,55.43504,0.0,0.115801,0.004742,0.672756,0.064339,0.088702,0.031953,0.021706,United Arab Emirates
3,`ajman-02-ae,asia/dubai,25.41111,55.43504,1.0,0.137027,0.008245,0.593775,0.066983,0.143962,0.029433,0.020576,United Arab Emirates
4,`ar`ar-15-sa,asia/riyadh,30.97531,41.03808,0.0,0.126709,0.019092,0.711986,0.027177,0.083284,0.023746,0.008006,Saudi Arabia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,zurich-zh112-ch,europe/zurich,47.36667,8.55000,1.0,0.050774,0.002235,0.255058,0.129349,0.437428,0.033761,0.091395,Switzerland
5471,zwickau-13-de,europe/berlin,50.72724,12.48839,0.0,0.118323,0.008310,0.553897,0.086094,0.125446,0.071881,0.036049,Germany
5472,zwickau-13-de,europe/berlin,50.72724,12.48839,1.0,0.105689,0.009183,0.582490,0.068055,0.136838,0.063264,0.034481,Germany
5473,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,0.0,0.115759,0.003075,0.438510,0.093060,0.215188,0.054410,0.079999,Netherlands
5474,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,1.0,0.128108,0.002996,0.452828,0.076322,0.227367,0.042848,0.069530,Netherlands

In [12]:
df_ble = df_ble.set_index(
    ['location', 'region', 'country', 'lat', 'lon', 'prediction']
).stack().reset_index(name='emotion_value').rename(
    columns={'level_6': 'emotion'})
df_ble

,location,region,country,lat,lon,prediction,emotion,emotion_value
0,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,anger,0.157472
1,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,disgust,0.013708
2,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,fear,0.562638
3,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,joy,0.108387
4,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,neutral,0.108624
...,...,...,...,...,...,...,...,...
38320,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,fear,0.452828
38321,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,joy,0.076322
38322,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,neutral,0.227367
38323,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,sadness,0.042848
38324,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,surprise,0.069530

In [13]:
df_ble.to_csv('./Analysis/df_ble.csv')

In [14]:
df_blm['country'] = df_blm['region'].replace(region_to_countries)
df_blm

,location,region,lat,lon,prediction,status_id,code,user_id,probability,Author,...,# mv_fairness_vice_cheating,# mv_loyalty_virtue,# mv_loyalty_vice_betrayal,# mv_authority_virtue,# mv_authority_vice_subversion,# mv_sanctity_virtue,# mv_sanctity_vice_degradation,# mv_liberty_virtue,# mv_liberty_vice_oppression,country
0,`ajlun-20-jo,asia/amman,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,0.457980,1.231770e+18,...,0.000000,0.006944,0.0,0.000000,0.000000,0.000000,0.000000,0.006944,0.000000,Jordan
1,`ajlun-20-jo,asia/amman,32.33385,35.75238,1.0,1.597977e+18,125557.0,7.595172e+17,0.806991,7.595172e+17,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Jordan
2,`ajman-02-ae,asia/dubai,25.41111,55.43504,0.0,1.598431e+18,226172.0,5.599376e+17,0.395782,5.599376e+17,...,0.004608,0.082949,0.0,0.009217,0.000000,0.018433,0.000000,0.013825,0.013825,United Arab Emirates
3,`ajman-02-ae,asia/dubai,25.41111,55.43504,1.0,1.598691e+18,226172.0,4.721810e+17,0.801816,4.721810e+17,...,0.000000,0.021978,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,United Arab Emirates
4,`ar`ar-15-sa,asia/riyadh,30.97531,41.03808,0.0,1.598475e+18,148540.0,8.338579e+17,0.407643,8.338579e+17,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Saudi Arabia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5450,zurich-zh112-ch,europe/zurich,47.36667,8.55000,1.0,1.598110e+18,874800.0,1.469594e+18,0.837136,1.469594e+18,...,0.000966,0.118860,0.0,0.000966,0.000322,0.000805,0.000483,0.001772,0.003704,Switzerland
5451,zwickau-13-de,europe/berlin,50.72724,12.48839,0.0,1.598220e+18,406174.0,8.357741e+17,0.399713,8.357741e+17,...,0.021978,0.054945,0.0,0.010989,0.000000,0.010989,0.021978,0.021978,0.000000,Germany
5452,zwickau-13-de,europe/berlin,50.72724,12.48839,1.0,1.598796e+18,406174.0,1.246383e+18,0.834598,1.246383e+18,...,0.000000,0.018182,0.0,0.018182,0.000000,0.036364,0.018182,0.036364,0.000000,Germany
5453,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,0.0,1.598537e+18,317594.0,6.888100e+17,0.375085,6.888100e+17,...,0.007491,0.078652,0.0,0.011236,0.007491,0.022472,0.014981,0.011236,0.037453,Netherlands
5454,zwolle-15-nl,europe/amsterdam,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,0.818086,7.975768e+17,...,0.009009,0.081081,0.0,0.000000,0.000000,0.027027,0.000000,0.000000,0.009009,Netherlands

In [15]:
df_blm.columns

Index(['location', 'region', 'lat', 'lon', 'prediction', 'status_id', 'code',
       'user_id', 'probability', 'Author', 'twitter_id', '# mv_care_virtue',
       '# mv_care_vice_harm', '# mv_fairness_virtue',
       '# mv_fairness_vice_cheating', '# mv_loyalty_virtue',
       '# mv_loyalty_vice_betrayal', '# mv_authority_virtue',
       '# mv_authority_vice_subversion', '# mv_sanctity_virtue',
       '# mv_sanctity_vice_degradation', '# mv_liberty_virtue',
       '# mv_liberty_vice_oppression', 'country'],
      dtype='object')

In [22]:
df_blm = df_blm.set_index(
    ['location', 'region', 'country', 'lat', 'lon', 
     'prediction', 'status_id', 'code', 'user_id',
     'Author', 'twitter_id', 'probability']).stack().reset_index(
    name='moral_value').rename(columns={'level_12': 'moral_name'})
df_blm

,location,region,country,lat,lon,prediction,status_id,code,user_id,Author,twitter_id,probability,moral_name,moral_value
0,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,1.231770e+18,1.597892e+18,0.457980,# mv_care_virtue,0.000000
1,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,1.231770e+18,1.597892e+18,0.457980,# mv_care_vice_harm,0.000000
2,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,1.231770e+18,1.597892e+18,0.457980,# mv_fairness_virtue,0.000000
3,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,1.231770e+18,1.597892e+18,0.457980,# mv_fairness_vice_cheating,0.000000
4,`ajlun-20-jo,asia/amman,Jordan,32.33385,35.75238,0.0,1.597892e+18,125557.0,1.231770e+18,1.231770e+18,1.597892e+18,0.457980,# mv_loyalty_virtue,0.006944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65455,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,7.975768e+17,1.598430e+18,0.818086,# mv_authority_vice_subversion,0.000000
65456,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,7.975768e+17,1.598430e+18,0.818086,# mv_sanctity_virtue,0.027027
65457,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,7.975768e+17,1.598430e+18,0.818086,# mv_sanctity_vice_degradation,0.000000
65458,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,7.975768e+17,1.598430e+18,0.818086,# mv_liberty_virtue,0.000000
65459,zwolle-15-nl,europe/amsterdam,Netherlands,52.51250,6.09444,1.0,1.598430e+18,317594.0,7.975768e+17,7.975768e+17,1.598430e+18,0.818086,# mv_liberty_vice_oppression,0.009009

In [23]:
df_blm.to_csv('./Analysis/df_blm.csv')